### PR TITLE
CDC fixes

### LINKED ISSUE #747: [cms] "Share.copy" and "Share.copied" appear in front-end data modal
These should be changed to the CMS namespace (like `"CMS.Options.Direct link"` a couple of lines down), and they will also need to be added to the default locale file at `src/i18n/canon.js`

### LINKED ISSUE #750: [cms] horizontal scrolling in view data table is broken in IE
from @gtdane:

> Regarding the VIEW DATA, the left to right scroll bar is not enabled until user scrolls to bottom of display

### LINKED ISSUE #752: [cms] sticky sections do not disappear in IE when entering a new grouping

### PR DESCRIPTION
**Pull request by perpetualgrimace**
A lil' bundle of bugfixes which _should_ close IE issues #750 and #752, as well as the non-IE issue #747.

Disclaimer: since the JS is currently not executing in IE, I'm unable to check my work in that browser. But I'm pretty confident they'll be fixed once we can get visualizations to print and calculate sticky section dimensions. 😬

- closes #750
- closes #752
- closes #747

### CODE REVIEW

File: packages/cms/src/components/Profile.jsx [hunk 1]
```diff
@@ -92,7 +93,14 @@ class Profile extends Component {
...
   render() {
-    const {profile, loading} = this.state;
+    const {isIE, profile, loading} = this.state;
+
+    // IE check needed for position: sticky fallback
+    if (typeof window !== "undefined") {
+      if (/*@cc_on!@*/false || !!document.documentMode) { // eslint-disable-line spaced-comment
+        this.setState({isIE: true});
+      }
+    }
```
Comment (davelandry) [inline packages/cms/src/components/Profile.jsx]: using `setState` within the render function is a no-no... can this logic just be moved right into the constructor?

**Comment by davelandry** [comment]
@perpetualgrimace also, if you format your text in the body of the PR with "closes #X" explicitly, it will automagically close those issues when this PR is closed 😄 

(so please go back and reformat the text)

**Comment by perpetualgrimace** [comment]
Ah so it doesn't read that when I leave it in the commits, only in the PR?

File: packages/cms/src/components/Profile.jsx (hunk 1 above)
Comment (perpetualgrimace) [reply packages/cms/src/components/Profile.jsx]: Ah okay. Because we'd be needlessly updating the state every time we need to re-render the component?

Comment (perpetualgrimace) [reply packages/cms/src/components/Profile.jsx]: https://github.com/facebook/react/issues/5342

Comment (perpetualgrimace) [reply packages/cms/src/components/Profile.jsx]: Apparently setState in the constructor is also a no-no. How about moving it to a `componentDidMount()` lifecycle method?

**Comment by davelandry** [comment]
ahhh I see what you mean, yeah it should probably pick it up from the commits ¯\_(ツ)_/¯

**Comment by perpetualgrimace** [comment]
ie-sticky-section

**Comment by perpetualgrimace** [comment]
K, have verified both IE bugs are fixed.

File: packages/cms/src/components/Profile.jsx [hunk 2]
```diff
@@ -27,10 +27,20 @@ class Profile extends Component {
...
 
+  // IE check needed for position: sticky fallback
+  componentDidMount() {
+    if (typeof window !== "undefined") {
+      if (/*@cc_on!@*/false || !!document.documentMode) { // eslint-disable-line spaced-comment
+        this.setState({isIE: true});
+      }
+    }
+  }
+
```
Comment (davelandry) [inline packages/cms/src/components/Profile.jsx]: Having this in the `componentDidMount` means that IE will render once without this, and then after the component mounts it will trigger this and re-render, causing an additional render cycle in IE. The React lifecycle is:
* `constructor`
* `render`
* `componentDidMount`

Moving this to the `constructor` would solve this (no need to initialize it as `false`), but I think a better solution would be to do this detection completely outside of the component, way up at the top of the file with the imports (ie. `const isIE` instead of using state)

File: packages/cms/src/utils/isIE.js [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+    // will only return true for internet explorer
+    if (/*@cc_on!@*/false || !!document.documentMode) { // eslint-disable-line spaced-comment
+      isIE = true;
+    }
+  }
+
+  return isIE;
+}
+
+module.exports = isIE;
```
Comment (davelandry) [inline packages/cms/src/utils/isIE.js]: Ahh, I see you didn't test this in non-IE browsers 😉 

This file exports a _Function_, which based on the way that you reference it in all of your components (`isIE`), it will always return `true` because a JavaScript _Function_ is a "truthy" variable. In it's current form, you would have to invoke this function to actually get the value (`isIE()`), but that would be running this code on every single render in every single usage. Ideally, this function code just be the following, but please test this in IE and Chrome to confirm:

```js
/** check if the current browser is internet explorer */
let isIE = false;

// make sure the browser window exists
if (typeof window !== "undefined") {
  // will only return true for internet explorer
  if (/*@cc_on!@*/false || !!document.documentMode) { // eslint-disable-line spaced-comment
    isIE = true;
  }
}

module.exports = isIE;
```
