### PR TITLE
Issue 861 flat section hierarchy bugs

### LINKED ISSUE #861: [cms] flat section hierarchy bugs
- [x] only the first section is shown in the subnav
~- [ ] `.cp-main > *:only-child > *:nth-child(odd):not(.cp-grouping-section)` is too specific~ (it's gotta be that specific; fix in OEC)

### PR DESCRIPTION
**Pull request by perpetualgrimace**
Changes to subnav logic:

- If there are <2 groupings, each non-grouping section will be shown in the subnav
- If there are >2 groupings, only grouping sections will be shown in the subnav
- if there are <3 subnav items, the subnav will not be shown

Closes #861

### CODE REVIEW

File: packages/cms/src/components/sections/Hero.jsx [hunk 1]
```diff
@@ -82,7 +82,8 @@ class Hero extends Component {
       if (contents.stats.length > 0) {
         const statGroups = nest().key(d => d.title).entries(contents.stats);
 
-        statContent = <div className="cp-stat-group-wrapper cp-hero-stat-group-wrapper">
+        statContent = <div className={`cp-stat-group-wrapper cp-hero-stat-group-wrapper${statGroups.length === 1 ? " single-stat" : ""}`}>
+          {console.log(statGroups.length)}
```
Comment (davelandry) [inline packages/cms/src/components/sections/Hero.jsx]: remove this and we'll be good to go!

Comment (perpetualgrimace) [reply packages/cms/src/components/sections/Hero.jsx]: lol dangit
